---
title: "LIHC Sunnyvale Investigation"
author: "Haleigh Quinn"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Evaluating demographics in Census Block Groups within 5 mile radius of the site:
```{r}
library(tigris)
library(sf)
library(tidyverse)
library(mapview)
library(censusapi)
library(dplyr)
library(leaflet)
library(ggplot2)
library(plotly)
library(mapview)
# Narrowing down census block groups within a 5 mile radius of the site: 
projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"

cbgs <- block_groups("CA","Santa Clara") %>%
  st_transform(projection)

site <- cbgs %>%
  filter(GEOID == "060855087042") %>%
  st_centroid() %>%
  st_transform(projection)

neighborhood_cbgs <- site %>%
  st_buffer(26400) %>%
  cbgs[., ]

mapview(neighborhood_cbgs)


# Create Clean Sex by Age data frame within 5 mile radius:
Sys.setenv(CENSUS_KEY="6e3cadd908fdaf8f7d3d728f4faa99e738db811a")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  ) 

sc_sexbyage <-
getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*", 
    regionin = "state:06+county:085",
    vars = "group(B01001)"
)%>%
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>% 
  separate(
    label,
    into = c(NA,NA,"sex","age"),
    sep = "!!"
  ) %>% 
  filter(!is.na(age)) %>%  
  filter(cbg %in% neighborhood_cbgs$GEOID)

sc_elderly <- 
  sc_sexbyage %>% 
  mutate(
    elderly = 
      ifelse(
        age %in% c(
          "65 and 66 years",
          "67 to 69 years",
          "70 to 74 years",
          "75 to 79 years",
          "80 to 84 years",
          "85 years and over"
        ),
        estimate,
        NA
      )
  ) %>% 
  group_by(cbg) %>% 
  summarize(
    elderly = sum(elderly, na.rm = T),
    total_pop = sum(estimate, na.rm = T)
  ) %>% 
  mutate(
    percent_elderly = elderly/total_pop*100
  ) %>% 
  filter(!is.na(percent_elderly))



elderly_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    sc_elderly$percent_elderly
)

leaflet() %>% 
  addTiles() %>% 
  addPolygons(
    data = 
      sc_elderly %>% 
        left_join(
          neighborhood_cbgs %>% select(GEOID), 
          by = c("cbg" = "GEOID")
        ) %>% 
        st_as_sf() %>% 
        st_transform(4326),
    fillColor = ~elderly_pal (percent_elderly),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.5,
    weight = 1,
    label = ~paste0(
      round(percent_elderly), 
      "% over age 65"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = sc_elderly,
    pal = elderly_pal,
    values = ~percent_elderly,
    title = "% over 65"
  )


# Families receiving public assistance by family size within 5 miles of the site:
family_size <- 
  c(
    "2-person families", 
    "3-person families",
    "4-person families",
    "5-person families", 
    "6-person families", 
    "7-or-more-person families"
  )


sc_fm_assistance <-
getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "block group:*", 
    regionin = "state:06+county:085",
    vars = "group(B19123)"
)%>%
  mutate(
    cbg =
      paste0(state,county,tract,block_group)
  ) %>% 
  select(!c(GEO_ID,state,county,tract,block_group,NAME) & !ends_with(c("EA","MA","M"))) %>%
  pivot_longer(
    ends_with("E"),
    names_to = "variable",
    values_to = "estimate"
  ) %>%
  left_join(
    acs_vars_2019_5yr %>% 
      select(name, label), 
    by = c("variable" = "name")
  ) %>% 
  select(-variable) %>%  
  separate(
    label,
    into = c(NA,NA,"family_size","assistance_status"),
    sep = "!!"
  ) %>% 
   filter(!is.na(assistance_status)) %>% 
  filter(cbg %in% neighborhood_cbgs$GEOID)

#Filled Plot: 
sc_fm_assistance %>% 
  group_by(family_size, assistance_status) %>% 
  summarize(estimate = sum(estimate)) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = assistance_status %>% factor(),
      y = estimate,
      fill = family_size
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Public Assistance Status",
    y = "Proportion of families receiving public assistance",
    title = "Families Receiving Public Assistance by Size",
    fill = "Size of Family"
 ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  ) + scale_x_discrete(label = function(x) stringr::str_trunc(x, 12))


#Stacked Plot:
sc_fm_assistance %>% 
  group_by(family_size, assistance_status) %>% 
  summarize(estimate = sum(estimate)) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = assistance_status %>% factor(),
      y = estimate,
      fill = family_size
    ),
    stat = "identity",
    position = "stack"
  ) +
  labs(
    x = "Public Assistance Status",
    y = "Number of families receiving public assistance",
    title = "Families Receiving Public Assistance by Size",
    fill = "Size of Family"
 ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  ) + scale_x_discrete(label = function(x) stringr::str_trunc(x, 12))


# Poverty Status in the past 12 months by Race: County Level  
census_race_labels <- 
  c(
    "White Alone",
    "Black or African American",
    "American Indian and Alaska Native Alone",
    "Asian Alone",
    "Native Hawaiian and Other Pacific Islander Alone)",
    "Some Other Race Alone",
    "Two or More Races"
  )


sc_poverty_race <-
  1:7 %>% 
  map_dfr(function(x){
    getCensus(
      name = "acs/acs5",
      vintage = 2019,
      region = "county:085",
      regionin = "state:06",
      vars = paste0("group(B17001",LETTERS[x],")")
    ) %>%
      select(!c(GEO_ID,state,NAME) & !ends_with(c("EA","MA","M"))) %>%
      pivot_longer(
        ends_with("E"),
        names_to = "variable",
        values_to = "estimate"
      ) %>%
      left_join(
        acs_vars_2019_5yr %>% 
          select(name, label), 
        by = c("variable" = "name")
      ) %>% 
      select(-variable) %>% 
      separate(
        label,
        into = c(NA, NA, "income", "sex", "age"),
        sep = "!!" 
      ) %>% filter(!is.na(age)) %>% 
      filter(!is.na(income)) %>% 
      mutate(race = census_race_labels[x])
    })
    
# Filled Plot: 
  sc_poverty_race %>% 
  group_by(income, race) %>% 
  summarize(estimate = sum(estimate)) %>% 
  ggplot() +
  geom_bar(
    aes(
      x = income %>% factor(),
      y = estimate,
      fill = race
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Income level in relation to poverty level",
    y = "Race of Respondents",
    title = "Poverty Status in the Past 12 Months",
    fill = "Race "
 ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  
 
  
# Chart: Percentage of Young Adults in Poverty SC County
sc_poverty_youngadult <- 
  sc_poverty_race %>% 
  mutate(
    youngadult = 
      ifelse(
        age %in% c(
          "25 to 34 years",
          "35 to 44 years"
        ),
        estimate,
        NA
      )
  ) %>% 
  group_by(race, income) %>% 
  summarize(
    youngadult = sum(youngadult, na.rm = T),
    total_pop = sum(estimate, na.rm = T)
  ) %>% 
  mutate(
    percent_youngadult = youngadult/total_pop*100
  ) %>% 
  filter(!is.na(percent_youngadult)) %>% 
  filter(!is.na(income))

#Pie Chart: 

youngadult_pov_chart <- 
  sc_poverty_youngadult%>% 
        filter(income %in% "Income in the past 12 months below poverty level:") %>% 
        group_by(income, race) %>% 
        summarize(percent_youngadult = sum(percent_youngadult))

youngadult_pov_fig <- 
  plot_ly(youngadult_pov_chart, labels = ~race, values = ~percent_youngadult,
          type = 'pie', 
          textposition = 'outside', 
          textinfo = 'percent', 
          outsidetextfont = list(color = '#404040'),
          hoverinfo = 'text', 
          text = ~paste(percent_youngadult, 'respondents'), 
          marker = list(colors = colors, 
                        line = list(color = '#FFFFFF', width = 0.5)), 
          showlegend = TRUE)


youngadult_pov_fig <- 
  youngadult_pov_fig %>% 
  layout(title = "% Respondents 24-34 below the poverty line in the past 12 months",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE, cex.lab = 0.5),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))




youngadult_pov_fig


# Chart: Percentage of Elderly in Poverty SC County
sc_poverty_elderly <- 
  sc_poverty_race %>% 
  mutate(
    elderly = 
      ifelse(
        age %in% c(
          "65 to 74 years",
          "75 years and older"
        ),
        estimate,
        NA
      )
  ) %>% 
  group_by(race, income) %>% 
  summarize(
    elderly = sum(elderly, na.rm = T),
    total_pop = sum(estimate, na.rm = T)
  ) %>% 
  mutate(
    percent_elderly = elderly/total_pop*100
  ) %>% 
  filter(!is.na(percent_elderly)) %>% 
  filter(!is.na(income))

#Pie Chart: 

elderly_pov_chart <- 
  sc_poverty_elderly%>% 
        filter(income %in% "Income in the past 12 months below poverty level:") %>% 
        group_by(income, race) %>% 
        summarize(percent_elderly = sum(percent_elderly))

elderly_pov_fig <- 
  plot_ly(elderly_pov_chart, labels = ~race, values = ~percent_elderly,
          type = 'pie', 
          textposition = 'outside', 
          textinfo = 'percent', 
          outsidetextfont = list(color = '#404040'),
          hoverinfo = 'text', 
          text = ~paste(percent_elderly, 'respondents'), 
          marker = list(colors = colors, 
                        line = list(color = '#FFFFFF', width = 0.5)), 
          showlegend = TRUE)


elderly_pov_fig <- 
  elderly_pov_fig %>% 
  layout(title = "% Respondents above 65 below the poverty line in the past 12 months",
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE, cex.lab = 0.5),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))




elderly_pov_fig








```


## Review: Geospatial Mapping 
```{r}
library(tigris)
library(sf)
library(tidyverse)
library(mapview)
library(censusapi)

# Narrowing down census block groups within a 5 mile radius of the site: 
projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs"

cbgs <- block_groups("CA","Santa Clara") %>%
  st_transform(projection)

site <- cbgs %>%
  filter(GEOID == "060855087042") %>%
  st_centroid() %>%
  st_transform(projection)

neighborhood_cbgs <- site %>%
  st_buffer(26400) %>%
  cbgs[., ]


  filter(block_groups %in%
  neighborhood_cbgs$GEOID)






```



